server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://cindy-db.cxc8yjsomhxw.ap-northeast-2.rds.amazonaws.com/cindyDB?autoReconnect=true
    username: admin
    password: My&sw01057556!
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전